### ISSUE TITLE
builder error: 'cimgui.h' not found

### ISSUE THREAD

**Issue by ccpplinux** [nsauzede/vig#2]
When I am trying to run the program vig/examples/mainig/mainig.v then I am getting the error message "builder error: 'cimgui.h' not found" although I have installed imgui as well as cimgui. The file cimgui.h is in the same folder in which mainig.v is saved. So what could be error? How to specify the path of the header file cimgui.h while running program of https://github.com/nsauzede/vig? Please help me so that I can start using this package.

**Comment by ccpplinux** [comment]
Yes I am able to install v properly. Even when I am running command v install nsauzede.vsdl2 as per instruction given on the page then it is also installing properly and I am able to run the example with command v run ~/.vmodules/nsauzede/vsdl2/examples/tvintris/tvintris.v. Similarly when I executed the command v install nsauzede.vig then it also worked. However when I am trying to run the command v run ~/.vmodules/nsauzede/vig/examples/mainig/mainig.v then I am getting following error message:

builder error: 'cimgui.h' not found

I think something is wrong with cimgui installation. Can you please give me a hint?

**Comment by nsauzede** [comment]
> 
> 
> Thanks for reply. When I am running the command make mrproper all then I am getting following error:
> 
> cc -std=gnu99 -w -I ./thirdparty/stdatomic/nix -o v1.exe ./vc/v.c -lm -lpthread ./v1.exe -no-parallel -o v2.exe cmd/v cmd/v/v.v:6:1: builder error: bad module definition: cmd/v/v.v imports module "help" but /home/ccpplinux/Nextcloud/VLang/vig/examples/mainig/sdl2test/v/cmd/v/help/help.v is defined as module `examples.mainig.sdl2test.v.cmd.v.help` 4 | module main 5 | 6 | import help | ~~~~~~~~~~~ 7 | import os 8 | import term make[1]: *** [GNUmakefile:94: all] Error 1 make[1]: Leaving directory '/home/ccpplinux/Nextcloud/VLang/vig/examples/mainig/sdl2test/v' /home/ccpplinux/Nextcloud/VLang/vig/examples/mainig/sdl2test touch nsauzede/vsdl2/v.mod ./v/v install nsauzede.vsdl2 make: ./v/v: No such file or directory make: *** [Makefile:150: /home/ccpplinux/.vmodules/nsauzede/vsdl2/v.mod] Error 127

I think I now understand what happens : you seem to have cloned `sdl2test` within `vig`, which is itself a V module.
Don't do that. Because that seems to interfere with V compiler modules handling (unrelated to my actual `vig` project)
Please rather do this:
```
$ cd /home/ccpplinux/Nextcloud/VLang
$ git clone https://github.com/nsauzede/sdl2test.git
$ cd sdl2test ; make mrproper all ; ./mainig_v.exe
```

=> This is to ensure that my current `vig` project is working within `sdl2test` (which is the primarily dev setup), somewhere else than in my environment.

Then, I could try and figure out what's wrong with other use cases of `vig`.

Thanks.

**Comment by ccpplinux** [comment]
Thanks. Now it is working. I am able to run and view the output of the program mainig_v.exe. Thanks a lot.

**Comment by nsauzede** [comment]
Great.
Next, I have to investigate more why vig doesn't work when used standalone..

**Comment by Jah-On** [comment]
I have been able to get closer, but it appears that the V compiler has indeed changed and will not compile vig.v. See my issue on V's GitHub. I changed the header paths to the full path. I also switched `#include <SDL.h>` to `
#include <SDL/SDL.h>` which fixed the import issues.

**Comment by Jah-On** [comment]
i should note that I am also on Manjaro Linux too because it's the best ; ).

**Comment by nsauzede** [comment]
Hello all.

I pushed some commit to try and fix the issue

Please test & report

**Comment by nsauzede** [comment]
Forgot to mention that you should git clone vig and try as below:
```shell
$ mkdir -p ~/.vmodules/nsauzede
$ cd ~/.vmodules/nsauzede
$ git clone https://github.com/nsauzede/vig
$ cd vig
$ make
$ v run examples/mainig/mainig.v
```
Note that separate `nsauzede/vsdl2` should first be installed in .vmodules, too..

**Comment by Jah-On** [comment]
Sorry to burst your bubble, but I am still having issues. When running the last command you gave, I get the following:
`INFO: compile with `v -live examples/mainig/mainig.v `, if you want to use the [live] function imgui_frame .
==================
/tmp/v_1000/mainig.8113548928954748782.tmp.c:11124: warning: assignment from incompatible pointer type
tcc: error: undefined symbol '_ZN5ImGui17GetCurrentContextEv'
tcc: error: undefined symbol '_ZN5ImGui5GetIOEv'
tcc: error: undefined symbol '_ZN7ImGuiIO22AddInputCharactersUTF8EPKc'
tcc: error: undefined symbol '_ZN7ImGuiIO13AddFocusEventEb'
tcc: error: undefined symbol '_ZN5ImGui8MemAllocEm'
tcc: error: undefined symbol '_ZN5ImGui14IsAnyMouseDownEv'
tcc: error: undefined symbol '_ZN5ImGui14GetMouseCursorEv'
tcc: error: undefined symbol '_ZN5ImGui7MemFreeEPv'
tcc: error: undefined symbol '_ZN11ImFontAtlas18GetTexDataAsRGBA32EPPhPiS2_S2_'
tcc: error: undefined symbol '_Unwind_Resume'
tcc: error: undefined symbol '__gxx_personality_v0'
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
`

Thanks!

(sdl2 is installed)

**Comment by Jah-On** [comment]
Wow, that did not format correctly 😂, sorry!

**Comment by nsauzede** [comment]
@Jah-On can you please perform the following and put back the result ?
```
$ pwd
$ ls -l
```

Just to see where you run your command from and whether you have obtained the proper files..

**Comment by Jah-On** [comment]
@nsauzede 
pwd:
`/home/jah-on/.vmodules/nsauzede/vig`

ls -l:
`total 2424
-rw-r--r-- 1 jah-on jah-on    1072 Nov 13 23:59 LICENSE
-rw-r--r-- 1 jah-on jah-on    1691 Nov 13 23:59 Makefile
-rw-r--r-- 1 jah-on jah-on     820 Nov 13 23:59 README.md
drwxr-xr-x 1 jah-on jah-on     280 Nov 13 23:59 cimgui
-rw-r--r-- 1 jah-on jah-on  169990 Nov 13 23:59 cimgui.h
-rwxr-xr-x 1 jah-on jah-on 1660576 Nov 13 23:59 cimgui.so
drwxr-xr-x 1 jah-on jah-on      12 Nov 13 23:59 examples
-rw-r--r-- 1 jah-on jah-on    3443 Nov 13 23:59 imgui_impl_opengl3.h
-rw-r--r-- 1 jah-on jah-on   30736 Nov 13 23:59 imgui_impl_opengl3.o
-rw-r--r-- 1 jah-on jah-on    1677 Nov 13 23:59 imgui_impl_sdl.h
-rw-r--r-- 1 jah-on jah-on   15456 Nov 13 23:59 imgui_impl_sdl.o
-rw-r--r-- 1 jah-on jah-on  563286 Nov 13 23:59 libcimgui.a
-rw-r--r-- 1 jah-on jah-on      58 Nov 13 23:59 v.mod
-rw-r--r-- 1 jah-on jah-on    4909 Nov 13 23:59 vig.v`

**Comment by nsauzede** [comment]
hmm
now this is strange;
I've got the same kind of results on my Ubuntu 21.10...
I'm sorry but I'm afraid I have no clues...

**Comment by Jah-On** [comment]
> hmm
> now this is strange;
> I've got the same kind of results on my Ubuntu 21.10...
> I'm sorry but I'm afraid I have no clues...

I have an issue on the V repository for cimgui. You should post your findings there and maybe they can tweak the compiler.

**Comment by phcreery** [comment]
Solved my issue
I had to change 
`cmake .. && make` to `cmake .. && cmake --build . --target all`
